### ISSUE TITLE
RAG流程

### ISSUE THREAD

**Issue by chenboju** [JustinHsu1019/RAG_Search_Weights#1]
您好，想請問關於RAG流程的問題
先說明我認知的RAG，是當LLM無法準確回答問題時，才需要做RAG，如果LLM可以直接回答的話，則不做RAG。
那麼請問在RAG過程中，User-query會先進入LLM嗎??
或是直接進入RAG的流程??
附上我畫的RAG流程
https://github.com/chenboju/RAG/blob/main/RAG%E9%81%8E%E7%A8%8B.png

**Comment by JustinHsu1019** [comment]
> 您好，想請問關於RAG流程的問題
> 
> 先說明我認知的RAG，是當LLM無法準確回答問題時，才需要做RAG，如果LLM可以直接回答的話，則不做RAG。
> 
> 那麼請問在RAG過程中，User-query會先進入LLM嗎??
> 
> 或是直接進入RAG的流程??
> 
> 附上我畫的RAG流程
> 
> https://github.com/chenboju/RAG/blob/main/RAG%E9%81%8E%E7%A8%8B.png

我目前做 RAG 主要都是使用者提問的流程中只經過一次 LLM，所以我是直接將問題送入 VDB 檢索，再將 Top k 和 query 一起送給 LLM 判斷，但在 Prompt 中會加入「If the passage is irrelevant to the answer, you may ignore it.」 

省略檢索+增加一次 LLM 訪問 vs 檢索+一次 LLM
成本上就是後者較有利

而且最重要的是你用 LLM 也無法準確判斷出它到底是否真的「知道」，很可能只是「幻覺」

**Comment by chenboju** [comment]
了解，感謝
